---
image: docker:25.0.4-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  NO_PROXY: "gitlab.teamdev.huds.su"

services:
  - name: docker:25.0.4-dind
    command: ["--tls=false"]

# before_script:
#   - docker info

stages:
  - build
  - test
  - delivery
  - clean

build-job:
  stage: build
  when: always
  script:
    - docker build . --target build --platform linux/amd64 -t bivi/backend:build
    - docker image rm -f bivi/backend:build

lint-job:
  stage: test
  when: always
  script:
    - docker build . --target lint --platform linux/amd64 -t bivi/backend:lint
    - docker image rm -f bivi/backend:lint

.allure-reports:
  before_script:
    - rm -rf $(pwd)/test-reports/*
    - mkdir -p $(pwd)/test-reports
    - export ALLURE_OUTPUT_PATH=$(pwd)/test-reports
  artifacts:
    paths:
      - test-reports
    expire_in: 30 days

e2e-test-job:
  stage: test
  when: always
  needs:
    - build-job
  extends: .allure-reports
  script:
    - docker build . --target e2e-test --platform linux/amd64 -t bivi/backend:e2e-test
    - docker create --name extract bivi/backend:e2e-test
    - docker cp extract:/test-reports .
    - docker rm extract
    - docker image rm -f bivi/backend:e2e-test

build-image-job:
  stage: delivery
  when: manual
  needs:
    - lint-job
    - e2e-test-job
  script:
    - docker build . --target app --platform linux/amd64 -t $CI_REGISTRY/bivi/backend:$CI_COMMIT_SHORT_SHA

push-image-job:
  stage: delivery
  when: manual
  needs:
    - build-image-job
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker images
    - docker push $CI_REGISTRY/bivi/backend:$CI_COMMIT_SHORT_SHA
    - docker logout

clean-image-job:
  stage: clean
  when: manual
  needs:
    - build-image-job
  script:
    - docker image rm -f $CI_REGISTRY/bivi/backend:$CI_COMMIT_SHORT_SHA
    - docker images
