run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - deadcode # Deprecated
    - depguard
    - exhaustivestruct # Deprecated
    - exhaustruct
    - gci
    - godot
    - gofumpt
    - goimports
    - golint # Deprecated
    - ifshort # Deprecated
    - interfacer # Deprecated
    - maligned # Deprecated
    - nosnakecase # Deprecated
    - scopelint # Deprecated
    - structcheck # Deprecated
    - varcheck # Deprecated
