// Code generated by swaggo/swag. DO NOT EDIT.

package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "andreysapozhkov535@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/client/logs": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Client API"
                ],
                "summary": "Upload client logs.",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Body with log file",
                        "name": "logs",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Log file saved"
                    },
                    "413": {
                        "description": "Request file size is more than 5Mb",
                        "schema": {
                            "$ref": "#/definitions/gitlab_teamdev_huds_su_bivi_backend_internal_pkg_app_errors.FiberError"
                        }
                    },
                    "422": {
                        "description": "Cannot get Multipart form file from request",
                        "schema": {
                            "$ref": "#/definitions/gitlab_teamdev_huds_su_bivi_backend_internal_pkg_app_errors.FiberError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_teamdev_huds_su_bivi_backend_internal_pkg_app_errors.FiberError"
                        }
                    }
                }
            }
        },
        "/streams": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Stream API"
                ],
                "summary": "Get stream descriptions.",
                "responses": {
                    "200": {
                        "description": "List of available streams",
                        "schema": {
                            "$ref": "#/definitions/internal_stream_delivery.StreamsInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_teamdev_huds_su_bivi_backend_internal_pkg_app_errors.FiberError"
                        }
                    }
                }
            }
        },
        "/streams/qualities": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Stream API"
                ],
                "summary": "Get stream qualities.",
                "responses": {
                    "200": {
                        "description": "List of available stream qualities",
                        "schema": {
                            "$ref": "#/definitions/internal_stream_delivery.QualitiesDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/gitlab_teamdev_huds_su_bivi_backend_internal_pkg_app_errors.FiberError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gitlab_teamdev_huds_su_bivi_backend_internal_models.StreamDescription": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "San Francisco"
                },
                "playlistPath": {
                    "type": "string",
                    "example": "/content/U2FuIEZyYW5jaXNjbw==/playlist.m3u8"
                },
                "previewPath": {
                    "type": "string",
                    "example": "/content/U2FuIEZyYW5jaXNjbw==/preview.png"
                }
            }
        },
        "gitlab_teamdev_huds_su_bivi_backend_internal_pkg_app_errors.FiberError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "internal_stream_delivery.QualitiesDTO": {
            "type": "object",
            "properties": {
                "qualities": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_stream_delivery.QualityDTO"
                    }
                }
            }
        },
        "internal_stream_delivery.QualityDTO": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer",
                    "example": 720
                },
                "preferredPeakBitRate": {
                    "type": "integer",
                    "example": 4200000
                }
            }
        },
        "internal_stream_delivery.StreamsInfo": {
            "type": "object",
            "properties": {
                "streams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/gitlab_teamdev_huds_su_bivi_backend_internal_models.StreamDescription"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "bivi API",
	Description:      "This is bivi backend API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
