basePath: /api/v1
info:
  contact:
    email: andreysapozhkov535@gmail.com
    name: API Support
  description: This is bivi backend API.
  title: bivi API
  version: 0.1.0
paths: {}
schemes:
- http
swagger: "2.0"
