basePath: /api/v1
definitions:
  gitlab_teamdev_huds_su_bivi_backend_internal_models.StreamDescription:
    properties:
      name:
        example: San Francisco
        type: string
      playlistPath:
        example: /content/U2FuIEZyYW5jaXNjbw==/playlist.m3u8
        type: string
      previewPath:
        example: /content/U2FuIEZyYW5jaXNjbw==/preview.png
        type: string
    type: object
  gitlab_teamdev_huds_su_bivi_backend_internal_pkg_app_errors.FiberError:
    properties:
      error:
        type: string
    type: object
  internal_stream_delivery.QualitiesDTO:
    properties:
      qualities:
        items:
          $ref: '#/definitions/internal_stream_delivery.QualityDTO'
        type: array
    type: object
  internal_stream_delivery.QualityDTO:
    properties:
      height:
        example: 720
        type: integer
      preferredPeakBitRate:
        example: 4200000
        type: integer
    type: object
  internal_stream_delivery.StreamsInfo:
    properties:
      streams:
        items:
          $ref: '#/definitions/gitlab_teamdev_huds_su_bivi_backend_internal_models.StreamDescription'
        type: array
    type: object
info:
  contact:
    email: andreysapozhkov535@gmail.com
    name: API Support
  description: This is bivi backend API.
  title: bivi API
  version: 0.1.0
paths:
  /client/logs:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body with log file
        in: formData
        name: logs
        required: true
        type: file
      responses:
        "200":
          description: Log file saved
        "413":
          description: Request file size is more than 5Mb
          schema:
            $ref: '#/definitions/gitlab_teamdev_huds_su_bivi_backend_internal_pkg_app_errors.FiberError'
        "422":
          description: Cannot get Multipart form file from request
          schema:
            $ref: '#/definitions/gitlab_teamdev_huds_su_bivi_backend_internal_pkg_app_errors.FiberError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gitlab_teamdev_huds_su_bivi_backend_internal_pkg_app_errors.FiberError'
      summary: Upload client logs.
      tags:
      - Client API
  /streams:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: List of available streams
          schema:
            $ref: '#/definitions/internal_stream_delivery.StreamsInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gitlab_teamdev_huds_su_bivi_backend_internal_pkg_app_errors.FiberError'
      summary: Get stream descriptions.
      tags:
      - Stream API
  /streams/qualities:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: List of available stream qualities
          schema:
            $ref: '#/definitions/internal_stream_delivery.QualitiesDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gitlab_teamdev_huds_su_bivi_backend_internal_pkg_app_errors.FiberError'
      summary: Get stream qualities.
      tags:
      - Stream API
schemes:
- http
swagger: "2.0"
